// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/clipsync/proto/clipsync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncPayload carries clipboard content between peers via HTTP POST /sync
// and GET /clip response.
type SyncPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formats       []*ClipFormat          `protobuf:"bytes,1,rep,name=formats,proto3" json:"formats,omitempty"`
	Files         []*FileRef             `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPayload) Reset() {
	*x = SyncPayload{}
	mi := &file_internal_clipsync_proto_clipsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPayload) ProtoMessage() {}

func (x *SyncPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clipsync_proto_clipsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPayload.ProtoReflect.Descriptor instead.
func (*SyncPayload) Descriptor() ([]byte, []int) {
	return file_internal_clipsync_proto_clipsync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncPayload) GetFormats() []*ClipFormat {
	if x != nil {
		return x.Formats
	}
	return nil
}

func (x *SyncPayload) GetFiles() []*FileRef {
	if x != nil {
		return x.Files
	}
	return nil
}

// ClipFormat holds a single clipboard representation keyed by MIME type.
type ClipFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MimeType      string                 `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"` // "text/plain", "text/html", "image/png", etc.
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipFormat) Reset() {
	*x = ClipFormat{}
	mi := &file_internal_clipsync_proto_clipsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipFormat) ProtoMessage() {}

func (x *ClipFormat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clipsync_proto_clipsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipFormat.ProtoReflect.Descriptor instead.
func (*ClipFormat) Descriptor() ([]byte, []int) {
	return file_internal_clipsync_proto_clipsync_proto_rawDescGZIP(), []int{1}
}

func (x *ClipFormat) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ClipFormat) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// FileRef describes a file attached to the clipboard payload.
type FileRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // file content embedded in payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRef) Reset() {
	*x = FileRef{}
	mi := &file_internal_clipsync_proto_clipsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRef) ProtoMessage() {}

func (x *FileRef) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clipsync_proto_clipsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRef.ProtoReflect.Descriptor instead.
func (*FileRef) Descriptor() ([]byte, []int) {
	return file_internal_clipsync_proto_clipsync_proto_rawDescGZIP(), []int{2}
}

func (x *FileRef) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileRef) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileRef) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Beacon is the UDP discovery message sent on broadcast and unicast reply.
type Beacon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magic         string                 `protobuf:"bytes,1,opt,name=magic,proto3" json:"magic,omitempty"` // "CLPSYNC2"
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`       // node ID
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`  // HTTP listen port
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`   // clipboard content hash
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"` // group isolation key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Beacon) Reset() {
	*x = Beacon{}
	mi := &file_internal_clipsync_proto_clipsync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Beacon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beacon) ProtoMessage() {}

func (x *Beacon) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clipsync_proto_clipsync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beacon.ProtoReflect.Descriptor instead.
func (*Beacon) Descriptor() ([]byte, []int) {
	return file_internal_clipsync_proto_clipsync_proto_rawDescGZIP(), []int{3}
}

func (x *Beacon) GetMagic() string {
	if x != nil {
		return x.Magic
	}
	return ""
}

func (x *Beacon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Beacon) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Beacon) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Beacon) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// DiscoverRequest is the HTTP POST /discover body for firewall-safe
// peer registration.
type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_internal_clipsync_proto_clipsync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clipsync_proto_clipsync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_internal_clipsync_proto_clipsync_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiscoverRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DiscoverRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DiscoverRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

var File_internal_clipsync_proto_clipsync_proto protoreflect.FileDescriptor

const file_internal_clipsync_proto_clipsync_proto_rawDesc = "" +
	"\n" +
	"&internal/clipsync/proto/clipsync.proto\x12\bclipsync\"f\n" +
	"\vSyncPayload\x12.\n" +
	"\aformats\x18\x01 \x03(\v2\x14.clipsync.ClipFormatR\aformats\x12'\n" +
	"\x05files\x18\x02 \x03(\v2\x11.clipsync.FileRefR\x05files\"=\n" +
	"\n" +
	"ClipFormat\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"S\n" +
	"\aFileRef\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"l\n" +
	"\x06Beacon\x12\x14\n" +
	"\x05magic\x18\x01 \x01(\tR\x05magic\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\"_\n" +
	"\x0fDiscoverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05groupB4Z2github.com/mmdemirbas/mesh/internal/clipsync/protob\x06proto3"

var (
	file_internal_clipsync_proto_clipsync_proto_rawDescOnce sync.Once
	file_internal_clipsync_proto_clipsync_proto_rawDescData []byte
)

func file_internal_clipsync_proto_clipsync_proto_rawDescGZIP() []byte {
	file_internal_clipsync_proto_clipsync_proto_rawDescOnce.Do(func() {
		file_internal_clipsync_proto_clipsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_clipsync_proto_clipsync_proto_rawDesc), len(file_internal_clipsync_proto_clipsync_proto_rawDesc)))
	})
	return file_internal_clipsync_proto_clipsync_proto_rawDescData
}

var file_internal_clipsync_proto_clipsync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_clipsync_proto_clipsync_proto_goTypes = []any{
	(*SyncPayload)(nil),     // 0: clipsync.SyncPayload
	(*ClipFormat)(nil),      // 1: clipsync.ClipFormat
	(*FileRef)(nil),         // 2: clipsync.FileRef
	(*Beacon)(nil),          // 3: clipsync.Beacon
	(*DiscoverRequest)(nil), // 4: clipsync.DiscoverRequest
}
var file_internal_clipsync_proto_clipsync_proto_depIdxs = []int32{
	1, // 0: clipsync.SyncPayload.formats:type_name -> clipsync.ClipFormat
	2, // 1: clipsync.SyncPayload.files:type_name -> clipsync.FileRef
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_clipsync_proto_clipsync_proto_init() }
func file_internal_clipsync_proto_clipsync_proto_init() {
	if File_internal_clipsync_proto_clipsync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_clipsync_proto_clipsync_proto_rawDesc), len(file_internal_clipsync_proto_clipsync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_clipsync_proto_clipsync_proto_goTypes,
		DependencyIndexes: file_internal_clipsync_proto_clipsync_proto_depIdxs,
		MessageInfos:      file_internal_clipsync_proto_clipsync_proto_msgTypes,
	}.Build()
	File_internal_clipsync_proto_clipsync_proto = out.File
	file_internal_clipsync_proto_clipsync_proto_goTypes = nil
	file_internal_clipsync_proto_clipsync_proto_depIdxs = nil
}
