// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/filesync/proto/filesync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexExchange is sent during sync: each side pushes its index and receives
// the peer's index in the response.
type IndexExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	FolderId      string                 `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"` // Highest sequence number in this index
	Files         []*FileInfo            `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	Since         int64                  `protobuf:"varint,5,opt,name=since,proto3" json:"since,omitempty"` // Only include entries with sequence > since (delta mode)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexExchange) Reset() {
	*x = IndexExchange{}
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexExchange) ProtoMessage() {}

func (x *IndexExchange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexExchange.ProtoReflect.Descriptor instead.
func (*IndexExchange) Descriptor() ([]byte, []int) {
	return file_internal_filesync_proto_filesync_proto_rawDescGZIP(), []int{0}
}

func (x *IndexExchange) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IndexExchange) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *IndexExchange) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *IndexExchange) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *IndexExchange) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

// FileInfo describes a single file (or a deletion tombstone) in the index.
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Relative to folder root, forward-slash separated
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MtimeNs       int64                  `protobuf:"varint,3,opt,name=mtime_ns,json=mtimeNs,proto3" json:"mtime_ns,omitempty"` // Unix nanoseconds
	Sha256        []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`                   // 32 bytes
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`                // Tombstone flag
	Sequence      int64                  `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`              // Per-file monotonic counter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_internal_filesync_proto_filesync_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMtimeNs() int64 {
	if x != nil {
		return x.MtimeNs
	}
	return 0
}

func (x *FileInfo) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *FileInfo) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *FileInfo) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_internal_filesync_proto_filesync_proto protoreflect.FileDescriptor

const file_internal_filesync_proto_filesync_proto_rawDesc = "" +
	"\n" +
	"&internal/filesync/proto/filesync.proto\x12\bfilesync\"\xa5\x01\n" +
	"\rIndexExchange\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\x12(\n" +
	"\x05files\x18\x04 \x03(\v2\x12.filesync.FileInfoR\x05files\x12\x14\n" +
	"\x05since\x18\x05 \x01(\x03R\x05since\"\x9b\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x19\n" +
	"\bmtime_ns\x18\x03 \x01(\x03R\amtimeNs\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x03R\bsequenceB4Z2github.com/mmdemirbas/mesh/internal/filesync/protob\x06proto3"

var (
	file_internal_filesync_proto_filesync_proto_rawDescOnce sync.Once
	file_internal_filesync_proto_filesync_proto_rawDescData []byte
)

func file_internal_filesync_proto_filesync_proto_rawDescGZIP() []byte {
	file_internal_filesync_proto_filesync_proto_rawDescOnce.Do(func() {
		file_internal_filesync_proto_filesync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_filesync_proto_filesync_proto_rawDesc), len(file_internal_filesync_proto_filesync_proto_rawDesc)))
	})
	return file_internal_filesync_proto_filesync_proto_rawDescData
}

var file_internal_filesync_proto_filesync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_filesync_proto_filesync_proto_goTypes = []any{
	(*IndexExchange)(nil), // 0: filesync.IndexExchange
	(*FileInfo)(nil),      // 1: filesync.FileInfo
}
var file_internal_filesync_proto_filesync_proto_depIdxs = []int32{
	1, // 0: filesync.IndexExchange.files:type_name -> filesync.FileInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_filesync_proto_filesync_proto_init() }
func file_internal_filesync_proto_filesync_proto_init() {
	if File_internal_filesync_proto_filesync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_filesync_proto_filesync_proto_rawDesc), len(file_internal_filesync_proto_filesync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_filesync_proto_filesync_proto_goTypes,
		DependencyIndexes: file_internal_filesync_proto_filesync_proto_depIdxs,
		MessageInfos:      file_internal_filesync_proto_filesync_proto_msgTypes,
	}.Build()
	File_internal_filesync_proto_filesync_proto = out.File
	file_internal_filesync_proto_filesync_proto_goTypes = nil
	file_internal_filesync_proto_filesync_proto_depIdxs = nil
}
