// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/filesync/proto/filesync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexExchange is sent during sync: each side pushes its index and receives
// the peer's index in the response.
type IndexExchange struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	FolderId        string                 `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Sequence        int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"` // Highest sequence number in this index
	Files           []*FileInfo            `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	Since           int64                  `protobuf:"varint,5,opt,name=since,proto3" json:"since,omitempty"`                                             // Only include entries with sequence > since (delta mode)
	Page            int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`                                               // 0-based page number
	TotalPages      int32                  `protobuf:"varint,7,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`                 // Total pages (0 or 1 = single page, legacy compat)
	Fetch           bool                   `protobuf:"varint,8,opt,name=fetch,proto3" json:"fetch,omitempty"`                                             // True = client is fetching a server response page
	Epoch           string                 `protobuf:"bytes,9,opt,name=epoch,proto3" json:"epoch,omitempty"`                                              // Random ID regenerated on index creation; used to detect index loss
	ProtocolVersion uint32                 `protobuf:"varint,10,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // Filesync wire protocol version. Current: 1. Mismatches are rejected.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IndexExchange) Reset() {
	*x = IndexExchange{}
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexExchange) ProtoMessage() {}

func (x *IndexExchange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexExchange.ProtoReflect.Descriptor instead.
func (*IndexExchange) Descriptor() ([]byte, []int) {
	return file_internal_filesync_proto_filesync_proto_rawDescGZIP(), []int{0}
}

func (x *IndexExchange) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IndexExchange) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *IndexExchange) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *IndexExchange) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *IndexExchange) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *IndexExchange) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *IndexExchange) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *IndexExchange) GetFetch() bool {
	if x != nil {
		return x.Fetch
	}
	return false
}

func (x *IndexExchange) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

func (x *IndexExchange) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

// FileInfo describes a single file (or a deletion tombstone) in the index.
type FileInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Path     string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Relative to folder root, forward-slash separated
	Size     int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MtimeNs  int64                  `protobuf:"varint,3,opt,name=mtime_ns,json=mtimeNs,proto3" json:"mtime_ns,omitempty"` // Unix nanoseconds
	Sha256   []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`                   // 32 bytes
	Deleted  bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`                // Tombstone flag
	Sequence int64                  `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`              // Per-device ordering only (delta shortcut). Conflict semantics live in version.
	Mode     uint32                 `protobuf:"varint,7,opt,name=mode,proto3" json:"mode,omitempty"`                      // Unix permission bits (e.g., 0644)
	// prev_path is a single-use rename hint (R1 Phase 2). Set by the sender
	// when it detects that a new path has the same filesystem inode as a
	// tombstoned entry; the receiver uses it to apply a local rename (plus
	// optional /delta against the old content) instead of a full re-download.
	// Empty when no rename was detected. Peers that do not understand this
	// field ignore it and download normally (safe fallback via proto3
	// unknown-field tolerance).
	PrevPath string `protobuf:"bytes,8,opt,name=prev_path,json=prevPath,proto3" json:"prev_path,omitempty"`
	// C6: per-file vector clock. Each Counter carries a device_id (10-char
	// Crockford base32) and the number of local writes observed on that
	// device. Conflict detection compares vectors by strict domination.
	Version       []*Counter `protobuf:"bytes,9,rep,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_internal_filesync_proto_filesync_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMtimeNs() int64 {
	if x != nil {
		return x.MtimeNs
	}
	return 0
}

func (x *FileInfo) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *FileInfo) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *FileInfo) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetPrevPath() string {
	if x != nil {
		return x.PrevPath
	}
	return ""
}

func (x *FileInfo) GetVersion() []*Counter {
	if x != nil {
		return x.Version
	}
	return nil
}

// Counter is a single entry in a vector clock: how many writes device_id
// has observed for a given file. See docs/filesync/DESIGN-v1.md §1.
type Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 10-char Crockford base32
	Value         uint64                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counter) Reset() {
	*x = Counter{}
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counter.ProtoReflect.Descriptor instead.
func (*Counter) Descriptor() ([]byte, []int) {
	return file_internal_filesync_proto_filesync_proto_rawDescGZIP(), []int{2}
}

func (x *Counter) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Counter) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// BundleRequest lists file paths to download in a single round-trip (P19).
// Response is a tar+zstd stream; files absent from the tar are retried individually.
type BundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleRequest) Reset() {
	*x = BundleRequest{}
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleRequest) ProtoMessage() {}

func (x *BundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleRequest.ProtoReflect.Descriptor instead.
func (*BundleRequest) Descriptor() ([]byte, []int) {
	return file_internal_filesync_proto_filesync_proto_rawDescGZIP(), []int{3}
}

func (x *BundleRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *BundleRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// BlockSignatures is sent by the receiver to request a block-level delta.
// Each Block is a FastCDC chunk of the receiver's local file (see
// docs/filesync/DESIGN-v1.md §2). The sender chunks its own copy with
// the same deterministic parameters and returns the full chunk layout
// of its file; for each chunk whose hash the receiver already has,
// the data field stays empty.
type BlockSignatures struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"` // Total local file size
	Blocks        []*Block               `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`                      // FastCDC chunks of the local file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSignatures) Reset() {
	*x = BlockSignatures{}
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSignatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSignatures) ProtoMessage() {}

func (x *BlockSignatures) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSignatures.ProtoReflect.Descriptor instead.
func (*BlockSignatures) Descriptor() ([]byte, []int) {
	return file_internal_filesync_proto_filesync_proto_rawDescGZIP(), []int{4}
}

func (x *BlockSignatures) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *BlockSignatures) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BlockSignatures) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *BlockSignatures) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// Block identifies one FastCDC chunk. offset+length locate the bytes in
// the file that produced the chunk; hash is SHA-256 of the chunk bytes.
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"` // SHA-256, 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_internal_filesync_proto_filesync_proto_rawDescGZIP(), []int{5}
}

func (x *Block) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Block) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// DeltaResponse carries the sender's complete chunk layout. Chunks
// whose hash exists in the receiver's signatures are returned without
// data — the receiver reassembles them by looking up the hash in its
// own local chunks. Chunks new to the receiver carry data inline.
type DeltaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileSize      int64                  `protobuf:"varint,1,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"` // Total remote file size
	Blocks        []*DeltaBlock          `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`                      // Sender's full chunk list, in offset order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaResponse) Reset() {
	*x = DeltaResponse{}
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaResponse) ProtoMessage() {}

func (x *DeltaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaResponse.ProtoReflect.Descriptor instead.
func (*DeltaResponse) Descriptor() ([]byte, []int) {
	return file_internal_filesync_proto_filesync_proto_rawDescGZIP(), []int{6}
}

func (x *DeltaResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *DeltaResponse) GetBlocks() []*DeltaBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// DeltaBlock identifies one sender-side chunk. data is populated iff
// the receiver does not already have this hash. When raw is false
// (default), data is zstd-compressed; when raw is true, data is sent
// uncompressed because the source file's magic bytes indicate a format
// that is already compressed. See docs/filesync/DESIGN-v1.md §3.
type DeltaBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"` // Offset in the remote file
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"` // Chunk length in bytes (uncompressed)
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`      // SHA-256 of chunk content, 32 bytes (uncompressed)
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`      // Chunk bytes, empty if receiver has hash locally
	Raw           bool                   `protobuf:"varint,5,opt,name=raw,proto3" json:"raw,omitempty"`       // true = data is uncompressed (incompressible source)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaBlock) Reset() {
	*x = DeltaBlock{}
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaBlock) ProtoMessage() {}

func (x *DeltaBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filesync_proto_filesync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaBlock.ProtoReflect.Descriptor instead.
func (*DeltaBlock) Descriptor() ([]byte, []int) {
	return file_internal_filesync_proto_filesync_proto_rawDescGZIP(), []int{7}
}

func (x *DeltaBlock) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DeltaBlock) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *DeltaBlock) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *DeltaBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DeltaBlock) GetRaw() bool {
	if x != nil {
		return x.Raw
	}
	return false
}

var File_internal_filesync_proto_filesync_proto protoreflect.FileDescriptor

const file_internal_filesync_proto_filesync_proto_rawDesc = "" +
	"\n" +
	"&internal/filesync/proto/filesync.proto\x12\bfilesync\"\xb1\x02\n" +
	"\rIndexExchange\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\x12(\n" +
	"\x05files\x18\x04 \x03(\v2\x12.filesync.FileInfoR\x05files\x12\x14\n" +
	"\x05since\x18\x05 \x01(\x03R\x05since\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\a \x01(\x05R\n" +
	"totalPages\x12\x14\n" +
	"\x05fetch\x18\b \x01(\bR\x05fetch\x12\x14\n" +
	"\x05epoch\x18\t \x01(\tR\x05epoch\x12)\n" +
	"\x10protocol_version\x18\n" +
	" \x01(\rR\x0fprotocolVersion\"\xf9\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x19\n" +
	"\bmtime_ns\x18\x03 \x01(\x03R\amtimeNs\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x03R\bsequence\x12\x12\n" +
	"\x04mode\x18\a \x01(\rR\x04mode\x12\x1b\n" +
	"\tprev_path\x18\b \x01(\tR\bprevPath\x12+\n" +
	"\aversion\x18\t \x03(\v2\x11.filesync.CounterR\aversion\"<\n" +
	"\aCounter\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value\"B\n" +
	"\rBundleRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\"\x88\x01\n" +
	"\x0fBlockSignatures\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12'\n" +
	"\x06blocks\x18\x04 \x03(\v2\x0f.filesync.BlockR\x06blocks\"K\n" +
	"\x05Block\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\"Z\n" +
	"\rDeltaResponse\x12\x1b\n" +
	"\tfile_size\x18\x01 \x01(\x03R\bfileSize\x12,\n" +
	"\x06blocks\x18\x02 \x03(\v2\x14.filesync.DeltaBlockR\x06blocks\"v\n" +
	"\n" +
	"DeltaBlock\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x10\n" +
	"\x03raw\x18\x05 \x01(\bR\x03rawB4Z2github.com/mmdemirbas/mesh/internal/filesync/protob\x06proto3"

var (
	file_internal_filesync_proto_filesync_proto_rawDescOnce sync.Once
	file_internal_filesync_proto_filesync_proto_rawDescData []byte
)

func file_internal_filesync_proto_filesync_proto_rawDescGZIP() []byte {
	file_internal_filesync_proto_filesync_proto_rawDescOnce.Do(func() {
		file_internal_filesync_proto_filesync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_filesync_proto_filesync_proto_rawDesc), len(file_internal_filesync_proto_filesync_proto_rawDesc)))
	})
	return file_internal_filesync_proto_filesync_proto_rawDescData
}

var file_internal_filesync_proto_filesync_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_filesync_proto_filesync_proto_goTypes = []any{
	(*IndexExchange)(nil),   // 0: filesync.IndexExchange
	(*FileInfo)(nil),        // 1: filesync.FileInfo
	(*Counter)(nil),         // 2: filesync.Counter
	(*BundleRequest)(nil),   // 3: filesync.BundleRequest
	(*BlockSignatures)(nil), // 4: filesync.BlockSignatures
	(*Block)(nil),           // 5: filesync.Block
	(*DeltaResponse)(nil),   // 6: filesync.DeltaResponse
	(*DeltaBlock)(nil),      // 7: filesync.DeltaBlock
}
var file_internal_filesync_proto_filesync_proto_depIdxs = []int32{
	1, // 0: filesync.IndexExchange.files:type_name -> filesync.FileInfo
	2, // 1: filesync.FileInfo.version:type_name -> filesync.Counter
	5, // 2: filesync.BlockSignatures.blocks:type_name -> filesync.Block
	7, // 3: filesync.DeltaResponse.blocks:type_name -> filesync.DeltaBlock
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_filesync_proto_filesync_proto_init() }
func file_internal_filesync_proto_filesync_proto_init() {
	if File_internal_filesync_proto_filesync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_filesync_proto_filesync_proto_rawDesc), len(file_internal_filesync_proto_filesync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_filesync_proto_filesync_proto_goTypes,
		DependencyIndexes: file_internal_filesync_proto_filesync_proto_depIdxs,
		MessageInfos:      file_internal_filesync_proto_filesync_proto_msgTypes,
	}.Build()
	File_internal_filesync_proto_filesync_proto = out.File
	file_internal_filesync_proto_filesync_proto_goTypes = nil
	file_internal_filesync_proto_filesync_proto_depIdxs = nil
}
